{
  "ticker": "AAPL",
  "trade_date": null,
  "error": "duplicate base class TimeoutError",
  "traceback": "Traceback (most recent call last):\n  File \"/Users/bytedance/Documents/TradingAgents/trading-graph-server/execute_graph.py\", line 105, in execute_full_graph\n    from src.agent.graph.trading_graph import TradingAgentsGraph\n  File \"/Users/bytedance/Documents/TradingAgents/trading-graph-server/src/agent/graph/__init__.py\", line 3, in <module>\n    from .optimized_setup import OptimizedGraphBuilder as GraphSetup\n  File \"/Users/bytedance/Documents/TradingAgents/trading-graph-server/src/agent/graph/optimized_setup.py\", line 33, in <module>\n    from ..analysts.market_analyst_ultra_fast_async import create_market_analyst_ultra_fast_async as create_market_analyst\n  File \"/Users/bytedance/Documents/TradingAgents/trading-graph-server/src/agent/analysts/market_analyst_ultra_fast_async.py\", line 47, in <module>\n    import aioredis\n  File \"/opt/homebrew/lib/python3.11/site-packages/aioredis/__init__.py\", line 1, in <module>\n    from aioredis.client import Redis, StrictRedis\n  File \"/opt/homebrew/lib/python3.11/site-packages/aioredis/client.py\", line 32, in <module>\n    from aioredis.connection import (\n  File \"/opt/homebrew/lib/python3.11/site-packages/aioredis/connection.py\", line 33, in <module>\n    from .exceptions import (\n  File \"/opt/homebrew/lib/python3.11/site-packages/aioredis/exceptions.py\", line 14, in <module>\n    class TimeoutError(asyncio.TimeoutError, builtins.TimeoutError, RedisError):\nTypeError: duplicate base class TimeoutError\n",
  "timestamp": "2025-08-13T17:55:44.610991"
}